# Generated by Django 6.0.5 on 2026-05-15 14:23

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Cliente",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("nome", models.CharField(max_length=200)),
                ("nif", models.CharField(blank=True, max_length=20)),
                ("email", models.EmailField(max_length=254)),
                ("telefone", models.CharField(blank=True, max_length=30)),
                ("ativo", models.BooleanField(default=True)),
                ("criado_em", models.DateTimeField(auto_now_add=True)),
                ("actualizado_em", models.DateTimeField(auto_now=True)),
            ],
            options={
                "ordering": ["nome"],
            },
        ),
        migrations.CreateModel(
            name="Subscricao",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "plano",
                    models.CharField(
                        choices=[("BAS", "Basico"), ("PRO", "Profissional"), ("ENT", "Enterprise")],
                        default="BAS",
                        max_length=3,
                    ),
                ),
                (
                    "bd_rupturas_ativa",
                    models.BooleanField(
                        default=False, help_text="Extra pago: acesso a BD Esgotados Infarmed"
                    ),
                ),
                ("data_inicio", models.DateField()),
                ("data_fim", models.DateField(blank=True, null=True)),
                ("ativa", models.BooleanField(default=True)),
                (
                    "cliente",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="subscricao",
                        to="accounts.cliente",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="UserProfile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "role",
                    models.CharField(
                        choices=[
                            ("admin", "Administrador"),
                            ("compras", "Responsavel de Compras"),
                            ("farmacia", "Farmacia"),
                        ],
                        default="compras",
                        max_length=20,
                    ),
                ),
                (
                    "cliente",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="utilizadores",
                        to="accounts.cliente",
                    ),
                ),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="profile",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Farmacia",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("nome", models.CharField(max_length=200)),
                (
                    "localizacao_key",
                    models.CharField(
                        help_text="Valor exacto do campo LOCALIZACAO no Infoprex (ex: 'FARMACIA GUIA')",
                        max_length=100,
                    ),
                ),
                (
                    "alias",
                    models.CharField(help_text="Nome de apresentacao (ex: 'Guia')", max_length=100),
                ),
                ("ativa", models.BooleanField(default=True)),
                ("licenciada_ate", models.DateField(blank=True, null=True)),
                (
                    "cliente",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="farmacias",
                        to="accounts.cliente",
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "farmacias",
                "ordering": ["alias"],
                "unique_together": {("cliente", "localizacao_key")},
            },
        ),
    ]
