# Generated by Django 6.0.5 on 2026-05-15 14:24

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("accounts", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="ConfigLaboratorio",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("nome", models.CharField(max_length=200, unique=True)),
                (
                    "codigos_cla",
                    models.JSONField(help_text='Lista de codigos CLA. Ex: ["137", "2651"]'),
                ),
                ("ativo", models.BooleanField(default=True)),
            ],
            options={
                "verbose_name_plural": "configlaboratorios",
                "ordering": ["nome"],
            },
        ),
        migrations.CreateModel(
            name="ConfigPesoPreset",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("nome", models.CharField(max_length=100, unique=True)),
                ("pesos", models.JSONField(help_text="Lista de 4 pesos. Ex: [0.4, 0.3, 0.2, 0.1]")),
            ],
            options={
                "verbose_name_plural": "configpesopresets",
                "ordering": ["nome"],
            },
        ),
        migrations.CreateModel(
            name="SessaoProcessamento",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("criado_em", models.DateTimeField(auto_now_add=True)),
                ("num_ficheiros", models.IntegerField()),
                ("num_produtos", models.IntegerField()),
                ("num_farmacias", models.IntegerField()),
                ("lab_selecionados", models.JSONField(default=list)),
                ("modo_detalhado", models.BooleanField(default=False)),
                ("meses_previsao", models.FloatField(default=1.0)),
                (
                    "cliente",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="accounts.cliente"
                    ),
                ),
                (
                    "utilizador",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL
                    ),
                ),
            ],
            options={
                "ordering": ["-criado_em"],
            },
        ),
        migrations.CreateModel(
            name="ConfigLocalizacao",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "search_term",
                    models.CharField(
                        help_text="Termo de pesquisa no campo LOCALIZACAO do Infoprex",
                        max_length=200,
                    ),
                ),
                ("alias", models.CharField(help_text="Nome de apresentacao", max_length=100)),
                (
                    "cliente",
                    models.ForeignKey(
                        blank=True,
                        help_text="Se null, e uma config global (aplica-se a todos)",
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="localizacoes",
                        to="accounts.cliente",
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "configlocalizacaos",
                "ordering": ["search_term"],
                "unique_together": {("cliente", "search_term")},
            },
        ),
    ]
